language: ruby
script: 
  - "rake test"
  - "gem build arel.gemspec"
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
rvm:
  - rbx
  - jruby-head
  - 2.0.0
  - 2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  email: false
  irc:
    - "irc.freenode.org#rails-contrib"
